version: "3.7"
services:
  postgres:
    image: postgres:15.3
    container_name: postgres_simple
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openmetadata_network

volumes:
  postgres_data:

networks:
  openmetadata_network:
    external: true
    name: openmetadata-docker_app_net
